"""Adding new column to users

Revision ID: 958fbb8bf28a
Revises: 35a5734649ff
Create Date: 2020-08-18 08:03:47.384653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958fbb8bf28a'
down_revision = '35a5734649ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('uniqueid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uniqueid')

    # ### end Alembic commands ###
