"""empty message

Revision ID: bf7ba7f0326e
Revises: 14ee0169103d
Create Date: 2020-08-18 09:36:08.183969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ba7f0326e'
down_revision = '14ee0169103d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storeid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['storeid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('storeid')

    # ### end Alembic commands ###
