"""Changes in foreign keys

Revision ID: fcfc337880a1
Revises: bf7ba7f0326e
Create Date: 2020-08-18 11:21:28.974100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfc337880a1'
down_revision = 'bf7ba7f0326e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storename', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['storename'], ['name'])
        batch_op.drop_column('storeid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storeid', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['storeid'], ['id'])
        batch_op.drop_column('storename')

    # ### end Alembic commands ###
